import assert from 'assert';
import {mainParser} from '../src/js/code-analyzer';

const tester = (title, code, args, actual) =>
    it(title, () => assert.equal(JSON.stringify(mainParser(code, ((JSON.parse(args))))), actual));

describe('test Variable Declarator substitute', () => {
    tester('simple return', 'function foo(x){ return x; }', '{"x":1}', '{"nodes":[{"id":1,"label":"1: return x\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[],"con":[],"alt":[]}');
    tester('var decl', 'function foo(x, y, z){ let a = x + 1; return a; }', '{"x":1, "y":2, "z":3}', '{"nodes":[{"id":1,"label":"1:      a = x + 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: return a\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[1,2]],"con":[],"alt":[]}');
    tester('if statement', 'function foo(x, y, z){ let a = x + 34; if(x < 10){ x = x + 1; } return a; }', '{"x":1, "y":2, "z":3}', '{"nodes":[{"id":1,"label":"1:      a = x + 34\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":-2,"label":"","shape":"ellipse","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: x < 10","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3:     x = x + 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":4,"label":"4: return a\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[3,-2],[1,2],[-2,4]],"con":[[2,3]],"alt":[[2,-2]]}');
    tester('if false', 'function foo(x, y, z){ let a = x + 34; a = 1; if(x > 2){ x = x + 1; } else{ x = x - 1; } a++; return a; }', '{"x":1, "y":2, "z":3}','{"nodes":[{"id":1,"label":"1:      a = x + 34\\n    a = 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":-2,"label":"","shape":"ellipse","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: x > 2","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3:     x = x + 1\\n","shape":"box","color":{"background":"white","border":"black"}},{"id":4,"label":"4:     x = x - 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":5,"label":"5:     a++\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":6,"label":"6: return a\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[3,-2],[1,2],[4,-2],[5,6]],"con":[[2,3]],"alt":[[2,4]]}');
    tester('else if', 'function foo(x, y, z){ let a = x + 34; a = 1; if(x < 10){ x = x + 1; } else if (x > 5) { x = x - 1; } a++; return a; }','{"x":1, "y":2, "z":3}','{"nodes":[{"id":1,"label":"1:      a = x + 34\\n    a = 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":-2,"label":"","shape":"ellipse","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: x < 10","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3:     x = x + 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":4,"label":"4: x > 5","shape":"diamond","color":{"background":"white","border":"black"}},{"id":5,"label":"5:     x = x - 1\\n","shape":"box","color":{"background":"white","border":"black"}},{"id":6,"label":"6:     a++\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":7,"label":"7: return a\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[3,-2],[1,2],[5,-2],[6,7]],"con":[[2,3],[4,5]],"alt":[[2,4],[4,-2]]}');
    tester('no else', 'function foo(x, y, z){ let a = x + 34; a = 1; if(x > 2){ x = x + 1; } a++; return a; }','{"x":1, "y":2, "z":3}','{"nodes":[{"id":1,"label":"1:      a = x + 34\\n    a = 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":-2,"label":"","shape":"ellipse","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: x > 2","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3:     x = x + 1\\n","shape":"box","color":{"background":"white","border":"black"}},{"id":4,"label":"4:     a++\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":5,"label":"5: return a\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[3,-2],[1,2],[4,5]],"con":[[2,3]],"alt":[[2,-2]]}');
    tester('while', 'function foo(x, y, z){ let a = x + 34; while (x < 10){ x = x + 1; } return a; }', '{"x":1, "y":2, "z":3}', '{"nodes":[{"id":1,"label":"1:      a = x + 34\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: NULL","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3: x < 10","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":4,"label":"4:     x = x + 1\\n","shape":"box","color":{"background":"white","border":"black"}},{"id":5,"label":"5: return a\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[1,2],[2,3],[4,2]],"con":[[3,4]],"alt":[[3,5]]}');
    tester('update', 'function foo(x, y, z){ let a = x + 34; if(x < 10){ x = x + 1; } a++; return a; }','{"x":1, "y":2, "z":3}','{"nodes":[{"id":1,"label":"1:      a = x + 34\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":-2,"label":"","shape":"ellipse","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: x < 10","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3:     x = x + 1\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":4,"label":"4:     a++\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":5,"label":"5: return a\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[3,-2],[1,2],[4,5]],"con":[[2,3]],"alt":[[2,-2]]}');
    tester('example', 'function foo(x, y, z){ let a = x + 1; let b = a + y; let c = 0; if (b < z) { c = c + 5; } else if (b < z * 2) { c = c + x + 5; } else { c = c + z + 5; } return c; }', '{"x":1,"y":2,"z":3}', '{"nodes":[{"id":1,"label":"1:      a = x + 1\\n     b = a + y\\n     c = 0\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":-2,"label":"","shape":"ellipse","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: b < z","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3:     c = c + 5\\n","shape":"box","color":{"background":"white","border":"black"}},{"id":4,"label":"4: b < z * 2","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":5,"label":"5:     c = c + x + 5\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":6,"label":"6:     c = c + z + 5\\n","shape":"box","color":{"background":"white","border":"black"}},{"id":7,"label":"7: return c\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[3,-2],[1,2],[5,-2],[6,-2],[-2,7]],"con":[[2,3],[4,5]],"alt":[[2,4],[4,6]]}');
    tester('example2', 'function foo(x, y, z){ let a = x + 1; let b = a + y; let c = 0; while (a < z) { c = a + b; z = c * 2; a++; } return z; }','{"x":1, "y":2, "z":3}','{"nodes":[{"id":1,"label":"1:      a = x + 1\\n     b = a + y\\n     c = 0\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":2,"label":"2: NULL","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}},{"id":3,"label":"3: a < z","shape":"diamond","color":{"background":"MediumSeaGreen","border":"black"}},{"id":4,"label":"4:     c = a + b\\n    z = c * 2\\n    a++\\n","shape":"box","color":{"background":"white","border":"black"}},{"id":5,"label":"5: return z\\n","shape":"box","color":{"background":"MediumSeaGreen","border":"black"}}],"always":[[1,2],[2,3],[4,2]],"con":[[3,4]],"alt":[[3,5]]}');
});
